### ISSUE TITLE
Fails with FileNotFoundError

### ISSUE THREAD

**Issue by yolk** [iliakur/miteclock#3]
Hi Ilia,

miteclock looks very promising! 

When first calling it on the command line, it asks for the api.key as documented. But given the valid key, it then fails with an `FileNotFoundError`:

    FileNotFoundError: [Errno 2] No such file or directory: '/Users/[...]/.config/miteclock/apikey'

It seems the config files are not correctly set up!? I am running python 3.9.

**Comment by iliakur** [comment]
Hi Sebastian!

Thanks for reporting this, I was able to reproduce and fix it. Configuration loading is something where we can definitely use some more exposure to flush out the bugs.

Feel free to give it another whirl after upgrading:

```sh
pip install -U miteclock
```

Let me know how it goes!

**Comment by yolk** [comment]
Works now. Thanks!
